USE [DB_CONTROLADORIA]
GO
/****** Object:  StoredProcedure [dbo].[PRC_ENVIO_EMAIL_DIARIO_POR_DIRETORIA_AZURE]    Script Date: 21/05/2021 20:31:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--USE [DB_CONTROLADORIA]
--GO
--/****** Object:  StoredProcedure [dbo].[PRC_ENVIO_EMAIL_DIARIO]    Script Date: 15/03/2021 16:01:32 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO

ALTER PROCEDURE [dbo].[PRC_ENVIO_EMAIL_DIARIO_POR_DIRETORIA_AZURE] @INICIO_ANO DATE,@MES_ATUAL DATE,  @FIM_MES DATE, @AGRUPADOR VARCHAR(10),@STATUS INT, @FRASE_ADICIONAL VARCHAR(255)
AS

SET LANGUAGE PORTUGUÊS

--DECLARE @INICIO_ANO DATE = '2021-01-01'
--DECLARE @MES_ATUAL DATE = '2021-02-01'
--DECLARE @FIM_MES DATE = '2021-02-28'
--DECLARE @AGRUPADOR VARCHAR(10) = 'G12'
--DECLARE @STATUS INT = 0
--DECLARE @FRASE_ADICIONAL VARCHAR(255) = ''


DECLARE @LINK_ARQUIVO VARCHAR(800)
DECLARE @LINK_POWER_BI VARCHAR(1000)
DECLARE @DESTINATARIO VARCHAR(1000)
DECLARE @NOME_MES VARCHAR(1000)

--SET @NOME_MES = CONVERT(VARCHAR,LOWER(DATENAME( MONTH , @MES_ATUAL)))
SET @NOME_MES = UPPER(LEFT(CONVERT(VARCHAR,LOWER(DATENAME( MONTH , @MES_ATUAL))),1))+LOWER(SUBSTRING(CONVERT(VARCHAR,LOWER(DATENAME( MONTH , @MES_ATUAL))),2,LEN(CONVERT(VARCHAR,LOWER(DATENAME( MONTH , @MES_ATUAL))))))

SET @LINK_POWER_BI = 'https://app.powerbi.com/groups/me/reports/7266b629-19d8-47e4-a38d-47499b7b8b40?ctid=049f1d45-bc1e-473d-baf9-7630814546b0'
					
IF OBJECT_ID('TEMPDB..#TABELA_FILTRADA') IS NOT NULL
BEGIN
	DROP TABLE #TABELA_FILTRADA
END

IF OBJECT_ID('TEMPDB..#ORCADO_ANO') IS NOT NULL
BEGIN
	DROP TABLE #ORCADO_ANO
END

SELECT TOP 1 * INTO #TABELA_FILTRADA FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS A
TRUNCATE TABLE #TABELA_FILTRADA

SELECT TOP 1 AGRUPADOR,NATUREZA,[TIPO GAV],CONVERT(FLOAT,SUM(ORCADO)) AS ORCADO_ANO INTO #ORCADO_ANO FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS OT
WHERE YEAR(OT.MES) = YEAR(@INICIO_ANO) GROUP BY AGRUPADOR, NATUREZA,[TIPO GAV]TRUNCATE TABLE #ORCADO_ANO

DECLARE @ASSUNTO VARCHAR(255);

IF @AGRUPADOR <> 'G99'
	BEGIN
		
		INSERT INTO #TABELA_FILTRADA
		SELECT * FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS A
		WHERE A.MES BETWEEN @INICIO_ANO AND @FIM_MES AND A.AGRUPADOR = @AGRUPADOR

		DECLARE @NOME_AGRUPADOR VARCHAR(255)
		SET @NOME_AGRUPADOR = (SELECT [GRUPO DIRETORIA] FROM [AZURE].[ICSK-DB-GIBI-PROD].[dbo].[COR-BR_RESPONSAVEIS_COLETORES_DE_CUSTOS] WHERE [AGRUPADOR DIRETORIA] = @AGRUPADOR GROUP BY [GRUPO DIRETORIA])
		SET @LINK_ARQUIVO = (SELECT [LINK DO ARQUIVO] FROM [AZURE].[ICSK-DB-GIBI-PROD].[dbo].[COR-BR_RESPONSAVEIS_COLETORES_DE_CUSTOS] WHERE [AGRUPADOR DIRETORIA] = @AGRUPADOR  GROUP BY [LINK DO ARQUIVO])
		SET @DESTINATARIO = (SELECT [MALING] FROM [AZURE].[ICSK-DB-GIBI-PROD].[dbo].[COR-BR_RESPONSAVEIS_COLETORES_DE_CUSTOS] WHERE [AGRUPADOR DIRETORIA] = @AGRUPADOR GROUP BY MALING)
		SET @ASSUNTO = CONCAT('Report | Orçado X Realizado | '+@NOME_MES+' | ',@NOME_AGRUPADOR)
		--SELECT * FROM [DB_CONTROLADORIA].[dbo].[TB_AGRUPADOR_DIRETORIAS]
		--FILTA O ORÇAMENTO TOTAL POR DIRETORIA
		INSERT INTO #ORCADO_ANO
		SELECT 
			AGRUPADOR,
			NATUREZA,
			[TIPO GAV],
			CONVERT(FLOAT,SUM(ORCADO)) AS ORCADO_ANO
		FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS OT
		WHERE YEAR(OT.MES) = YEAR(@INICIO_ANO) AND OT.AGRUPADOR = @AGRUPADOR
		GROUP BY 
			AGRUPADOR,
			NATUREZA,
			[TIPO GAV]

	END
ELSE
	BEGIN
		
		INSERT INTO #TABELA_FILTRADA
		SELECT * FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS A
		WHERE A.MES BETWEEN @INICIO_ANO AND @FIM_MES
		
		SET @LINK_ARQUIVO = (SELECT [LINK DO ARQUIVO] FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_RESPONSAVEIS_COLETORES_DE_CUSTOS] WHERE [AGRUPADOR DIRETORIA] = @AGRUPADOR GROUP BY [LINK DO ARQUIVO])
		
		SET @DESTINATARIO = (SELECT MALING FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_RESPONSAVEIS_COLETORES_DE_CUSTOS] WHERE [AGRUPADOR DIRETORIA] = @AGRUPADOR GROUP BY MALING)
		SET @ASSUNTO = 'Report | Orçado X Realizado | '+@NOME_MES+' | YTD | Consolidado'

		--FILTRA O ORÇAMENTO TOTAL
		INSERT INTO #ORCADO_ANO
		SELECT 
			AGRUPADOR,
			NATUREZA,
			[TIPO GAV],
			CONVERT(FLOAT,SUM(ORCADO)) AS ORCADO_ANO
		FROM [AZURE].[ICSK-DB-GIBI-PROD].[DBO].[COR-BR_TB_RESULTADO_ORCADO_X_REALIZADO_MES] AS OT
		WHERE YEAR(OT.MES) = YEAR(@INICIO_ANO) --AND OT.AGRUPADOR NOT IN ('G02','G09','G10')
		GROUP BY 
			AGRUPADOR,
			NATUREZA,
			[TIPO GAV]

	END

--SELECT * FROM #TABELA_FILTRADA

DECLARE @TIPO VARCHAR(1)= '''N'''
DECLARE @CULTURA VARCHAR(10) = '''pt-BR'''

SET @TIPO = 'N'
SET @CULTURA = 'pt-BR'

--REALIZADO MÊS
DECLARE @DESPESAS_COM_ESCRITORIO_R DECIMAL(18,5)
DECLARE @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R DECIMAL(18,2)
DECLARE @DESPESAS_COM_CONSULTORIA_R DECIMAL(18,5)
DECLARE @OUTRAS_DESPESAS_R DECIMAL(18,5)
DECLARE @DESPESAS_VIAGENS_R DECIMAL(18,5)
DECLARE @DESPESAS_TI_TELEFONIA_RELATIVOS_R DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_GERENCIAVEL_MES DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_RECEITA_MES DECIMAL(18,5)

DECLARE @ATIVO_FIXO_DEPRE_AMORTIZACAO_R DECIMAL(18,5)
DECLARE @IMPOSTOS_PAGOS_R DECIMAL(18,5)
DECLARE @DESPESAS_FINANCEIRAS_R DECIMAL(18,5)
DECLARE @RECEITAS_FINANCEIRAS_R DECIMAL(18,5)
DECLARE @PROVISOES_TRIBUTARIAS_R DECIMAL(18,5)
DECLARE @RECEITA_COM_LOCACAO_R DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES DECIMAL(18,5)


--ORÇADO MÊS
DECLARE @DESPESAS_COM_ESCRITORIO_O DECIMAL(18,5)
DECLARE @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O DECIMAL(18,5)
DECLARE @DESPESAS_COM_CONSULTORIA_O DECIMAL(18,5)
DECLARE @OUTRAS_DESPESAS_O DECIMAL(18,5)
DECLARE @DESPESAS_VIAGENS_O DECIMAL(18,5)
DECLARE @DESPESAS_TI_TELEFONIA_RELATIVOS_O DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_GERENCIAVEL_MES DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_RECEITA_MES DECIMAL(18,5)

DECLARE @ATIVO_FIXO_DEPRE_AMORTIZACAO_O DECIMAL(18,5)
DECLARE @IMPOSTOS_PAGOS_O DECIMAL(18,5)
DECLARE @DESPESAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @RECEITAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @PROVISOES_TRIBUTARIAS_O DECIMAL(18,5)
DECLARE @RECEITA_COM_LOCACAO_O DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_NAO_GERENCIAVEL_MES DECIMAL(18,5)


--REALIZADO ANO (ACUMULADO)
DECLARE @ACU_DESPESAS_COM_ESCRITORIO_R DECIMAL(18,5)
DECLARE @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R DECIMAL(18,2)
DECLARE @ACU_DESPESAS_COM_CONSULTORIA_R DECIMAL(18,5)
DECLARE @ACU_OUTRAS_DESPESAS_R DECIMAL(18,5)
DECLARE @ACU_DESPESAS_VIAGENS_R DECIMAL(18,5)
DECLARE @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_RECEITA_ACUMULADO DECIMAL(18,5)

DECLARE @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R DECIMAL(18,5)
DECLARE @ACU_IMPOSTOS_PAGOS_R DECIMAL(18,5)
DECLARE @ACU_DESPESAS_FINANCEIRAS_R DECIMAL(18,5)
DECLARE @ACU_RECEITAS_FINANCEIRAS_R DECIMAL(18,5)
DECLARE @ACU_PROVISOES_TRIBUTARIAS_R DECIMAL(18,5)
DECLARE @ACU_RECEITA_COM_LOCACAO_R DECIMAL(18,5)
DECLARE @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)

--ORÇADO ANO (ACUMULADO)
DECLARE @ACU_DESPESAS_COM_ESCRITORIO_O DECIMAL(18,5)
DECLARE @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O DECIMAL(18,5)
DECLARE @ACU_DESPESAS_COM_CONSULTORIA_O DECIMAL(18,5)
DECLARE @ACU_OUTRAS_DESPESAS_O DECIMAL(18,5)
DECLARE @ACU_DESPESAS_VIAGENS_O DECIMAL(18,5)
DECLARE @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_RECEITA_ACUMULADO DECIMAL(18,5)

DECLARE @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O DECIMAL(18,5)
DECLARE @ACU_IMPOSTOS_PAGOS_O DECIMAL(18,5)
DECLARE @ACU_DESPESAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @ACU_RECEITAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @ACU_PROVISOES_TRIBUTARIAS_O DECIMAL(18,5)
DECLARE @ACU_RECEITA_COM_LOCACAO_O DECIMAL(18,5)
DECLARE @TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)

--ORCADO TOTAL ANO
DECLARE @OT_DESPESAS_COM_ESCRITORIO_O DECIMAL(18,5)
DECLARE @OT_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O DECIMAL(18,5)
DECLARE @OT_DESPESAS_COM_CONSULTORIA_O DECIMAL(18,5)
DECLARE @OT_OUTRAS_DESPESAS_O DECIMAL(18,5)
DECLARE @OT_DESPESAS_VIAGENS_O DECIMAL(18,5)
DECLARE @OT_DESPESAS_TI_TELEFONIA_RELATIVOS_O DECIMAL(18,5)
DECLARE @OT_ORCADO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)
DECLARE @OT_ORCADO_RECEITA_ACUMULADO DECIMAL(18,5)

DECLARE @OT_ATIVO_FIXO_DEPRE_AMORTIZACAO_O DECIMAL(18,5)
DECLARE @OT_IMPOSTOS_PAGOS_O DECIMAL(18,5)
DECLARE @OT_DESPESAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @OT_RECEITAS_FINANCEIRAS_O DECIMAL(18,5)
DECLARE @OT_PROVISOES_TRIBUTARIAS_O DECIMAL(18,5)
DECLARE @OT_RECEITA_COM_LOCACAO_O DECIMAL(18,5)
DECLARE @OT_ORCADO_NAO_GERENCIAVEL_ACUMULADO DECIMAL(18,5)

--REALIZADO
SELECT @DESPESAS_COM_ESCRITORIO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM ESCRITÓRIO' AND MES = @MES_ATUAL

SELECT @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM SALÁRIOS, ENCARGOS E BENEFÍCIOS' AND MES = @MES_ATUAL

SELECT @DESPESAS_COM_CONSULTORIA_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM CONSULTORIA' AND MES = @MES_ATUAL

SELECT @OUTRAS_DESPESAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'OUTRAS DESPESAS' AND MES = @MES_ATUAL

SELECT @DESPESAS_VIAGENS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM VIAGENS' AND MES = @MES_ATUAL

SELECT @DESPESAS_TI_TELEFONIA_RELATIVOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM TI, TELEFONIA E RELATIVOS' AND MES = @MES_ATUAL

SELECT @ATIVO_FIXO_DEPRE_AMORTIZACAO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'ATIVO FIXO / DEPRECIAÇÃO / AMORTIZAÇÃO' AND MES = @MES_ATUAL

SELECT @IMPOSTOS_PAGOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'IMPOSTOS PAGOS' AND MES = @MES_ATUAL

SELECT @DESPESAS_FINANCEIRAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS FINANCEIRAS' AND MES = @MES_ATUAL

SELECT @RECEITAS_FINANCEIRAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'RECEITAS FINANCEIRAS' AND MES = @MES_ATUAL

SELECT @PROVISOES_TRIBUTARIAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Provisões Tributárias/Cíveis e Trabalhistas' AND MES = @MES_ATUAL

SELECT @RECEITA_COM_LOCACAO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Receitas com Locação' AND MES = @MES_ATUAL

SET @TOTAL_REALIZADO_RECEITA_MES = (@RECEITA_COM_LOCACAO_R)

SET @TOTAL_REALIZADO_GERENCIAVEL_MES = ( @DESPESAS_COM_ESCRITORIO_R + @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R + @DESPESAS_COM_CONSULTORIA_R + @OUTRAS_DESPESAS_R + @DESPESAS_VIAGENS_R + @DESPESAS_TI_TELEFONIA_RELATIVOS_R) 

SET @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES =(@ATIVO_FIXO_DEPRE_AMORTIZACAO_R + @IMPOSTOS_PAGOS_R + @DESPESAS_FINANCEIRAS_R + @RECEITAS_FINANCEIRAS_R + @PROVISOES_TRIBUTARIAS_R )
--REALIZADO

--ORÇADO
SELECT @DESPESAS_COM_ESCRITORIO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM ESCRITÓRIO' AND MES = @MES_ATUAL

SELECT @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM SALÁRIOS, ENCARGOS E BENEFÍCIOS' AND MES = @MES_ATUAL

SELECT @DESPESAS_COM_CONSULTORIA_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM CONSULTORIA' AND MES = @MES_ATUAL

SELECT @OUTRAS_DESPESAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'OUTRAS DESPESAS' AND MES = @MES_ATUAL

SELECT @DESPESAS_VIAGENS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM VIAGENS' AND MES = @MES_ATUAL

SELECT @DESPESAS_TI_TELEFONIA_RELATIVOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM TI, TELEFONIA E RELATIVOS' AND MES = @MES_ATUAL

SELECT @ATIVO_FIXO_DEPRE_AMORTIZACAO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'ATIVO FIXO / DEPRECIAÇÃO / AMORTIZAÇÃO' AND MES = @MES_ATUAL

SELECT @IMPOSTOS_PAGOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'IMPOSTOS PAGOS' AND MES = @MES_ATUAL

SELECT @DESPESAS_FINANCEIRAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS FINANCEIRAS' AND MES = @MES_ATUAL

SELECT @RECEITAS_FINANCEIRAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'RECEITAS FINANCEIRAS' AND MES = @MES_ATUAL

SELECT @PROVISOES_TRIBUTARIAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Provisões Tributárias/Cíveis e Trabalhistas' AND MES = @MES_ATUAL

SELECT @RECEITA_COM_LOCACAO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Receitas com Locação' AND MES = @MES_ATUAL

SET @TOTAL_ORCADO_RECEITA_MES = (@RECEITA_COM_LOCACAO_O)

SET @TOTAL_ORCADO_GERENCIAVEL_MES = ( @DESPESAS_COM_ESCRITORIO_O + @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O + @DESPESAS_COM_CONSULTORIA_O + @OUTRAS_DESPESAS_O + @DESPESAS_VIAGENS_O + @DESPESAS_TI_TELEFONIA_RELATIVOS_O)					   
						  
SET @TOTAL_ORCADO_NAO_GERENCIAVEL_MES = (@ATIVO_FIXO_DEPRE_AMORTIZACAO_O + @IMPOSTOS_PAGOS_O + @DESPESAS_FINANCEIRAS_O + @RECEITAS_FINANCEIRAS_O + @PROVISOES_TRIBUTARIAS_O )
--ORÇADO

--REALIZADO ANO (ACUMULADO)
SELECT @ACU_DESPESAS_COM_ESCRITORIO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM ESCRITÓRIO' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM SALÁRIOS, ENCARGOS E BENEFÍCIOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_COM_CONSULTORIA_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM CONSULTORIA' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_OUTRAS_DESPESAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'OUTRAS DESPESAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_VIAGENS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM VIAGENS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM TI, TELEFONIA E RELATIVOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'ATIVO FIXO / DEPRECIAÇÃO / AMORTIZAÇÃO' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_IMPOSTOS_PAGOS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'IMPOSTOS PAGOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_FINANCEIRAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS FINANCEIRAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_RECEITAS_FINANCEIRAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'RECEITAS FINANCEIRAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_PROVISOES_TRIBUTARIAS_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Provisões Tributárias/Cíveis e Trabalhistas' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_RECEITA_COM_LOCACAO_R = ISNULL(ROUND(SUM(REALIZADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Receitas com Locação' AND MES >= @INICIO_ANO AND MES <= @FIM_MES 

SET @TOTAL_REALIZADO_RECEITA_ACUMULADO = (@ACU_RECEITA_COM_LOCACAO_R)

SET @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO = (@ACU_DESPESAS_COM_ESCRITORIO_R + @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R + @ACU_DESPESAS_COM_CONSULTORIA_R + @ACU_OUTRAS_DESPESAS_R + @ACU_DESPESAS_VIAGENS_R + @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R)

SET @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO = (@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R +  @ACU_IMPOSTOS_PAGOS_R + @ACU_DESPESAS_FINANCEIRAS_R + @ACU_RECEITAS_FINANCEIRAS_R + @ACU_PROVISOES_TRIBUTARIAS_R )
--REALIZADO ANO (ACUMULADO)

--ORÇADO ANO (ACUMULADO)
SELECT @ACU_DESPESAS_COM_ESCRITORIO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM ESCRITÓRIO' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM SALÁRIOS, ENCARGOS E BENEFÍCIOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_COM_CONSULTORIA_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM CONSULTORIA' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_OUTRAS_DESPESAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'OUTRAS DESPESAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_VIAGENS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM VIAGENS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS COM TI, TELEFONIA E RELATIVOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'ATIVO FIXO / DEPRECIAÇÃO / AMORTIZAÇÃO' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_IMPOSTOS_PAGOS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'IMPOSTOS PAGOS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_DESPESAS_FINANCEIRAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'DESPESAS FINANCEIRAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_RECEITAS_FINANCEIRAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'RECEITAS FINANCEIRAS' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_PROVISOES_TRIBUTARIAS_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Provisões Tributárias/Cíveis e Trabalhistas' AND MES >= @INICIO_ANO AND MES <= @FIM_MES

SELECT @ACU_RECEITA_COM_LOCACAO_O = ISNULL(ROUND(SUM(ORCADO),2, 1),0) FROM #TABELA_FILTRADA
WHERE NATUREZA = 'Receitas com Locação' AND MES >= @INICIO_ANO AND MES <= @FIM_MES 

SET @TOTAL_ORCADO_RECEITA_ACUMULADO = (@ACU_RECEITA_COM_LOCACAO_O)

SET @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO = (@ACU_DESPESAS_COM_ESCRITORIO_O + @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O + @ACU_DESPESAS_COM_CONSULTORIA_O + @ACU_OUTRAS_DESPESAS_O + @ACU_DESPESAS_VIAGENS_O + @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O)

SET @TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO = (@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O + @ACU_IMPOSTOS_PAGOS_O + @ACU_DESPESAS_FINANCEIRAS_O + @ACU_RECEITAS_FINANCEIRAS_O + @ACU_PROVISOES_TRIBUTARIAS_O )
--ORÇADO ANO (ACUMULADO)

--TOTAL ORÇADO PARA O ANO
SELECT @OT_DESPESAS_COM_ESCRITORIO_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS COM ESCRITÓRIO' 

SELECT @OT_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS COM SALÁRIOS, ENCARGOS E BENEFÍCIOS' 

SELECT @OT_DESPESAS_COM_CONSULTORIA_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS COM CONSULTORIA' 

SELECT @OT_OUTRAS_DESPESAS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'OUTRAS DESPESAS' 

SELECT @OT_DESPESAS_VIAGENS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS COM VIAGENS' 

SELECT @OT_DESPESAS_TI_TELEFONIA_RELATIVOS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS COM TI, TELEFONIA E RELATIVOS' 

SELECT @OT_ATIVO_FIXO_DEPRE_AMORTIZACAO_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'ATIVO FIXO / DEPRECIAÇÃO / AMORTIZAÇÃO' 

SELECT @OT_IMPOSTOS_PAGOS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'IMPOSTOS PAGOS' 

SELECT @OT_DESPESAS_FINANCEIRAS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'DESPESAS FINANCEIRAS' 

SELECT @OT_RECEITAS_FINANCEIRAS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'RECEITAS FINANCEIRAS' 

SELECT @OT_PROVISOES_TRIBUTARIAS_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'PROVISÕES TRIBUTÁRIAS/CÍVEIS E TRABALHISTAS'

SELECT @OT_RECEITA_COM_LOCACAO_O =  ISNULL(ROUND(SUM(ORCADO_ANO),2, 1),0) FROM #ORCADO_ANO
WHERE NATUREZA = 'Receitas com Locação'


SELECT @OT_ORCADO_RECEITA_ACUMULADO = (@OT_RECEITA_COM_LOCACAO_O)
SELECT @OT_ORCADO_GERENCIAVEL_ACUMULADO = (@OT_DESPESAS_COM_ESCRITORIO_O + @OT_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O + @OT_DESPESAS_COM_CONSULTORIA_O + @OT_OUTRAS_DESPESAS_O + @OT_DESPESAS_VIAGENS_O + @OT_DESPESAS_TI_TELEFONIA_RELATIVOS_O)
SELECT @OT_ORCADO_NAO_GERENCIAVEL_ACUMULADO = (@OT_ATIVO_FIXO_DEPRE_AMORTIZACAO_O + @OT_IMPOSTOS_PAGOS_O + @OT_DESPESAS_FINANCEIRAS_O + @OT_RECEITAS_FINANCEIRAS_O + @OT_PROVISOES_TRIBUTARIAS_O)


DECLARE @BODYTEXT VARCHAR(MAX)= '
<html>

  <head>
  	<style>
			  
				.tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;}
				.tg .tg-totaliza{font-weight:bold;font-family:Arial, Helvetica, sans-serif !important;;background-color:#D83135;color:#ffffff;border-color:#c0c0c0;text-align:left;vertical-align:top;font-size:12px}
				.tg .tg-separador{background-color:#ffffff;color:#ffffff;border-color:#F1F0F0;text-align:center;vertical-align:top;font-size:12px}
				.tg .tg-dl88{font-weight:bold;font-family:Arial, Helvetica, sans-serif !important;;background-color:#F1F0F0;border-color:#c0c0c0;text-align:center;vertical-align:top;font-size: 12px}
				.tg .tg-spsm{font-family:Arial, Helvetica, sans-serif !important;;border-color:#c0c0c0;text-align:center;vertical-align:top;font-size:12px}
				.tg .tg-0ibc{font-family:Arial, Helvetica, sans-serif !important;;border-color:#c0c0c0;text-align:left;vertical-align:top;font-size:12px}
				.tg td{font-family:Arial, sans-serif;font-size:12px;padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#363636}
				.tg th{font-family:Arial, sans-serif;font-size:12px;font-weight:normal;padding:5px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#363636;background-color:#F1F0F0;}
				.tg .tg-yvqh{font-weight:bold;font-family:Arial, Helvetica, sans-serif !important;;background-color:#D83135;border-color:#c0c0c0;color:#ffffff;text-align:center;vertical-align:top;font-size:12px}
				.tg .tg-somatd{font-weight:bold;font-family:Arial, Helvetica, sans-serif !important;color:#FFFFFF;;background-color:#3A3A3A;border-color:#c0c0c0;text-align:center;vertical-align:top;font-size:12px}
				.tg .tg-somatdd{font-weight:bold;font-family:Arial, Helvetica, sans-serif !important;color:#FFFFFF;;background-color:#3A3A3A;border-color:#c0c0c0;text-align:left;vertical-align:top;font-size:12px}

				.externa	{
				text-align: center;
				width: 100%;
								
				}
				.interna
				{
				display: inline-block;
				}

				.resumo{color:#ffffff}


				#mes{table-layout: fixed; width: 129px}
				#acumulado{table-layout: fixed; width: 129px}
				#natureza{table-layout: fixed; width: 348px}

				#tamanho1 {table-layout: fixed; width: 129px}
				#tamanho2 {table-layout: fixed; width: 129px}
				#tamanho3 {table-layout: fixed; width: 129px}
				#tamanho4 {table-layout: fixed; width: 129px}
				#tamanho5 {table-layout: fixed; width: 129px}
				#tamanho6 {table-layout: fixed; width: 129px}
				#tamanho7 {table-layout: fixed; width: 129px}
				#tamanho8 {table-layout: fixed; width: 129px}
				#tamanho9 {table-layout: fixed; width: 129px}
				#tamanho10 {table-layout: fixed; width: 129px}
				#tamanho11 {table-layout: fixed; width: 129px}
				#tamanho12 {table-layout: fixed; width: 129px}
				#tamanho13 {table-layout: fixed; width: 129px}
				#tamanho14 {table-layout: fixed; width: 129px}
				#tamanho15 {table-layout: fixed; width: 129px}
				#tamanho16 {table-layout: fixed; width: 129px}
				#tamanho18 {table-layout: fixed; width: 129px}
				#tamanho19 {table-layout: fixed; width: 129px}
				#tamanho17{table-layout: fixed; width: 348px}

				#separador{width: 1px}

				#cabecalho{width: 1590px}
				#rodape{width: 1490px}

				.bomdia{text-align:left;color:#4D4D4D}
				.usuariopbi{color:#4D4D4D;text-align:left;font-size:13px}

				.icones{text-align:left}
				.icon{}

		</style>
</head>
<body>
		


<div class="externa">
<div class="interna">	


		<p class="bomdia">Prezado(a), </p>

		<p class="bomdia">Segue anexo o Relatório diário de gastos administrativos acumulado até o momento. <a href="'+@LINK_ARQUIVO+'">Acesse para ver com mais detalhes.</a><br></p>

		<table border="1px" cellspacing="0" cellpadding="0">
		<tr>
			<td class="tg-dl88" id="natureza" ></td>
			<td class="tg-dl88" id="tamanho1" ></td>
			<td class="tg-dl88" id="tamanho2" ></td>
			<td class="tg-dl88" id="tamanho3" ></td>
			<td class="tg-dl88" id="tamanho4" ></td>
			<td class="tg-separador" ></td>
			<td class="tg-dl88" id="tamanho5" ></td>
			<td class="tg-dl88" id="tamanho6" ></td>
			<td class="tg-dl88" id="tamanho7" ></td>
			<td class="tg-dl88" id="tamanho8" ></td>
			<td class="tg-dl88" id="tamanho19" align="right" ><a href="'+@LINK_ARQUIVO+'" class="tg-spsm"><img class="tg-spsm" alt="Arquivo Excel" src="https://i.ibb.co/ZzQhF2j/iconexcel.png" width="30"  /></a><a href="'+@LINK_POWER_BI+'" class="tg-spsm"><img class="tg-spsm" alt="Arquivo Power BI" src="https://i.ibb.co/ScjH9PW/iconpbi.png" width="30"  /></a></td>
		</tr>
		</table>


		<img id="cabecalho" alt="Imagem não carregada / Imagen no cargada" src="https://i.ibb.co/55Xz1mC/cabecalho-v7.jpg" width="1520" />
		<br>
	<table class="tg">

		<tr>
			<th class="tg-dl88" id="mes" colspan="5" >'+CONVERT(VARCHAR,UPPER(DATENAME( MONTH , @MES_ATUAL)))+'</th>
			<th class="tg-separador" id="separador"></th>
			<th class="tg-dl88" id="acumulado" colspan="5">ACUMULADO </a><br></p> </th>
		</tr>



		'




SET @BODYTEXT = @BODYTEXT + '

		<tr>
			<td class="tg-dl88" id="natureza" >NATUREZA - GERENCIÁVEL</td>
			<td class="tg-dl88" id="tamanho1" >REALIZADO</td>
			<td class="tg-dl88" id="tamanho2" >ORÇADO</td>
			<td class="tg-dl88" id="tamanho3" >VAR (R$)</td>
			<td class="tg-dl88" id="tamanho4" >VAR (%)</td>
			<td class="tg-separador" ></td>
			<td class="tg-dl88" id="tamanho5" >REALIZADO</td>
			<td class="tg-dl88" id="tamanho6" >ORÇADO</td>
			<td class="tg-dl88" id="tamanho7" >VAR (R$)</td>
			<td class="tg-dl88" id="tamanho8" >VAR (%)</td>
			<td class="tg-dl88" id="tamanho19" >ORÇA. RESTANTE</td>
		</tr>
		<tr>
			<td class="tg-0ibc">Despesas com Escritório</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_ESCRITORIO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_ESCRITORIO_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_ESCRITORIO_O - @DESPESAS_COM_ESCRITORIO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_COM_ESCRITORIO_R/NULLIF(@DESPESAS_COM_ESCRITORIO_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_ESCRITORIO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_ESCRITORIO_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_ESCRITORIO_O - @ACU_DESPESAS_COM_ESCRITORIO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_COM_ESCRITORIO_R/NULLIF(@ACU_DESPESAS_COM_ESCRITORIO_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_COM_ESCRITORIO_O - @ACU_DESPESAS_COM_ESCRITORIO_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc">Despesas com Salários, Encargos e Benefícios</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O - @DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R/NULLIF(@DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O - @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R/NULLIF(@ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_O - @ACU_DESPESAS_SALARIOS_ENCARGOS_BENEFICIOS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc">Despesas com Consultoria</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_CONSULTORIA_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_CONSULTORIA_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_COM_CONSULTORIA_O - @DESPESAS_COM_CONSULTORIA_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_COM_CONSULTORIA_R/NULLIF(@DESPESAS_COM_CONSULTORIA_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_CONSULTORIA_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_CONSULTORIA_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_COM_CONSULTORIA_O - @ACU_DESPESAS_COM_CONSULTORIA_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_COM_CONSULTORIA_R/NULLIF(@ACU_DESPESAS_COM_CONSULTORIA_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_COM_CONSULTORIA_O - @ACU_DESPESAS_COM_CONSULTORIA_R, @TIPO,@CULTURA))+'</td>
		</tr>'
--Quebra para concatenação
SET @BODYTEXT = @BODYTEXT + '			
		<tr>
			<td class="tg-0ibc">Outras Despesas</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OUTRAS_DESPESAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OUTRAS_DESPESAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OUTRAS_DESPESAS_O - @OUTRAS_DESPESAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@OUTRAS_DESPESAS_R/NULLIF(@OUTRAS_DESPESAS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_OUTRAS_DESPESAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_OUTRAS_DESPESAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_OUTRAS_DESPESAS_O - @ACU_OUTRAS_DESPESAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_OUTRAS_DESPESAS_R/NULLIF(@ACU_OUTRAS_DESPESAS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_OUTRAS_DESPESAS_O - @ACU_OUTRAS_DESPESAS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc">Despesas com Viagens</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_VIAGENS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_VIAGENS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_VIAGENS_O - @DESPESAS_VIAGENS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_VIAGENS_R/NULLIF(@DESPESAS_VIAGENS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_VIAGENS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_VIAGENS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_VIAGENS_O - @ACU_DESPESAS_VIAGENS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_VIAGENS_R/NULLIF(@ACU_DESPESAS_VIAGENS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_VIAGENS_O - @ACU_DESPESAS_VIAGENS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc">Despesas com TI, Telefonia e relativos</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_TI_TELEFONIA_RELATIVOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_TI_TELEFONIA_RELATIVOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_TI_TELEFONIA_RELATIVOS_O - @DESPESAS_TI_TELEFONIA_RELATIVOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_TI_TELEFONIA_RELATIVOS_R/NULLIF(@DESPESAS_TI_TELEFONIA_RELATIVOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O - @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R/NULLIF(@ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_TI_TELEFONIA_RELATIVOS_O - @ACU_DESPESAS_TI_TELEFONIA_RELATIVOS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-totaliza">SUB TOTAL</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_GERENCIAVEL_MES - @TOTAL_REALIZADO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(ISNULL((@TOTAL_REALIZADO_GERENCIAVEL_MES / NULLIF(@TOTAL_ORCADO_GERENCIAVEL_MES,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_GERENCIAVEL_ACUMULADO - @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(ISNULL((@TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO / NULLIF(@TOTAL_ORCADO_GERENCIAVEL_ACUMULADO,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@OT_ORCADO_GERENCIAVEL_ACUMULADO - @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
		</tr>
		
		<tr>
			<td class="tg-somatdd">TOTAL</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES)-(@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES) , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(ISNULL(((@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES) / NULLIF((@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES),0)-1),0) *100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO, @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO)-(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO), @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(ISNULL(((@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO) / NULLIF((@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO),0)-1),0) *100, @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@OT_ORCADO_RECEITA_ACUMULADO + @OT_ORCADO_GERENCIAVEL_ACUMULADO)-(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO), @TIPO,@CULTURA))+'</td>
		</tr>


</table>
	<br>



	<table class="tg">

		<tr>
			<td class="tg-dl88" id="tamanho17">NATUREZA - NÃO GERENCIÁVEL</td>
			<td class="tg-dl88" id="tamanho9">REALIZADO</td>
			<td class="tg-dl88" id="tamanho10">ORÇADO</td>
			<td class="tg-dl88" id="tamanho11">VAR (R$)</td>
			<td class="tg-dl88" id="tamanho12">VAR (%)</td>
			<td class="tg-separador"></td>
			<td class="tg-dl88" id="tamanho13">REALIZADO</td>
			<td class="tg-dl88" id="tamanho14">ORÇADO</td>
			<td class="tg-dl88" id="tamanho15">VAR (R$)</td>
			<td class="tg-dl88" id="tamanho16">VAR (%)</td>
			<td class="tg-dl88" id="tamanho18">ORÇA. RESTANTE</td>
		</tr>
		<tr>
			<td class="tg-0ibc"> Ativo fixo / Depreciação / Amortização</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ATIVO_FIXO_DEPRE_AMORTIZACAO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ATIVO_FIXO_DEPRE_AMORTIZACAO_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ATIVO_FIXO_DEPRE_AMORTIZACAO_O - @ATIVO_FIXO_DEPRE_AMORTIZACAO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ATIVO_FIXO_DEPRE_AMORTIZACAO_R/NULLIF(@ATIVO_FIXO_DEPRE_AMORTIZACAO_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O - @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R/NULLIF(@ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_ATIVO_FIXO_DEPRE_AMORTIZACAO_O - @ACU_ATIVO_FIXO_DEPRE_AMORTIZACAO_R , @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc"> Impostos Pagos</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@IMPOSTOS_PAGOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@IMPOSTOS_PAGOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@IMPOSTOS_PAGOS_O - @IMPOSTOS_PAGOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@IMPOSTOS_PAGOS_R/NULLIF(@IMPOSTOS_PAGOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_IMPOSTOS_PAGOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_IMPOSTOS_PAGOS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_IMPOSTOS_PAGOS_O - @ACU_IMPOSTOS_PAGOS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_IMPOSTOS_PAGOS_R/NULLIF(@ACU_IMPOSTOS_PAGOS_O,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_IMPOSTOS_PAGOS_O - @ACU_IMPOSTOS_PAGOS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc"> Despesas Financeiras</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_FINANCEIRAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@DESPESAS_FINANCEIRAS_O - @DESPESAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@DESPESAS_FINANCEIRAS_R/NULLIF(@DESPESAS_FINANCEIRAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_FINANCEIRAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_DESPESAS_FINANCEIRAS_O - @ACU_DESPESAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_DESPESAS_FINANCEIRAS_R/NULLIF(@ACU_DESPESAS_FINANCEIRAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_DESPESAS_FINANCEIRAS_O - @ACU_DESPESAS_FINANCEIRAS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc"> Receitas Financeiras</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@RECEITAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@RECEITAS_FINANCEIRAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@RECEITAS_FINANCEIRAS_O - @RECEITAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@RECEITAS_FINANCEIRAS_R/NULLIF(@RECEITAS_FINANCEIRAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_RECEITAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_RECEITAS_FINANCEIRAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_RECEITAS_FINANCEIRAS_O - @ACU_RECEITAS_FINANCEIRAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_RECEITAS_FINANCEIRAS_R/NULLIF(@ACU_RECEITAS_FINANCEIRAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_RECEITAS_FINANCEIRAS_O - @ACU_RECEITAS_FINANCEIRAS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-0ibc"> Provisões Tributárias/Cíveis e Trabalhistas</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@PROVISOES_TRIBUTARIAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@PROVISOES_TRIBUTARIAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@PROVISOES_TRIBUTARIAS_O - @PROVISOES_TRIBUTARIAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@PROVISOES_TRIBUTARIAS_R/NULLIF(@PROVISOES_TRIBUTARIAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-separador"></td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_PROVISOES_TRIBUTARIAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_PROVISOES_TRIBUTARIAS_O , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@ACU_PROVISOES_TRIBUTARIAS_O - @ACU_PROVISOES_TRIBUTARIAS_R , @TIPO,@CULTURA))+'</td>
			<td class="tg-spsm">'+ISNULL(CONVERT(VARCHAR,FORMAT(ISNULL((@ACU_PROVISOES_TRIBUTARIAS_R/NULLIF(@ACU_PROVISOES_TRIBUTARIAS_O,0)-1),0)*100 , @TIPO,@CULTURA)),'0.00')+'</td>
			<td class="tg-spsm">'+CONVERT(VARCHAR,FORMAT(@OT_PROVISOES_TRIBUTARIAS_O - @ACU_PROVISOES_TRIBUTARIAS_R, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-totaliza">SUB TOTAL</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_NAO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_NAO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_NAO_GERENCIAVEL_MES - @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(ISNULL((@TOTAL_REALIZADO_NAO_GERENCIAVEL_MES / NULLIF(@TOTAL_ORCADO_NAO_GERENCIAVEL_MES,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO - @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(ISNULL((@TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO / NULLIF(@TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO,0)-1),0)*100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-yvqh">'+CONVERT(VARCHAR,FORMAT(@OT_ORCADO_NAO_GERENCIAVEL_ACUMULADO - @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO, @TIPO,@CULTURA))+'</td>
		</tr>
		<tr>
			<td class="tg-somatdd">TOTAL GERAL</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES + @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES + @TOTAL_ORCADO_NAO_GERENCIAVEL_MES , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES + @TOTAL_ORCADO_NAO_GERENCIAVEL_MES)-(@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES + @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES) , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(ISNULL(((@TOTAL_REALIZADO_RECEITA_MES + @TOTAL_REALIZADO_GERENCIAVEL_MES + @TOTAL_REALIZADO_NAO_GERENCIAVEL_MES) / NULLIF((@TOTAL_ORCADO_RECEITA_MES + @TOTAL_ORCADO_GERENCIAVEL_MES + @TOTAL_ORCADO_NAO_GERENCIAVEL_MES),0)-1),0) *100 , @TIPO,@CULTURA))+'</td>
			<td class="tg-separador"></td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO + @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO , @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO + @TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO, @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO + @TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO)-(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO + @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO), @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT(ISNULL(((@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO + @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO) / NULLIF((@TOTAL_ORCADO_RECEITA_ACUMULADO + @TOTAL_ORCADO_GERENCIAVEL_ACUMULADO + @TOTAL_ORCADO_NAO_GERENCIAVEL_ACUMULADO),0)-1),0) *100, @TIPO,@CULTURA))+'</td>
			<td class="tg-somatd">'+CONVERT(VARCHAR,FORMAT((@OT_ORCADO_RECEITA_ACUMULADO + @OT_ORCADO_GERENCIAVEL_ACUMULADO + @OT_ORCADO_NAO_GERENCIAVEL_ACUMULADO)-(@TOTAL_REALIZADO_RECEITA_ACUMULADO + @TOTAL_REALIZADO_GERENCIAVEL_ACUMULADO + @TOTAL_REALIZADO_NAO_GERENCIAVEL_ACUMULADO), @TIPO,@CULTURA))+'</td>
		</tr>

	</table>

</div>
</div>

<p class="bomdia"><span><b>Atenciosamente,<br>Controladoria</b><br></span></p>

</body>

</html>'

DECLARE @PREFIXO VARCHAR(255)

IF @STATUS = 1
BEGIN
	SET @PREFIXO = '[EM FECHAMENTO] '  --'[EM FECHAMENTO] '
END
ELSE IF @STATUS = 2
BEGIN
	SET @PREFIXO = '[FECHAMENTO] '
END
ELSE
	SET @PREFIXO = ''

SET @ASSUNTO = @PREFIXO + @ASSUNTO

BEGIN
EXEC MSDB.DBO.SP_SEND_DBMAIL  
@RECIPIENTS = @DESTINATARIO,
@COPY_RECIPIENTS = 'kleber.ribeiro@icsk.com;douglas.silva@icsk.com;anderson.silvestre@icsk.com;tiago.franca@icsk.com',
--@BLIND_COPY_RECIPIENTS  = 'douglas.silva@icsk.com',
@SUBJECT= @ASSUNTO,
@BODY = @BODYTEXT,
@BODY_FORMAT='HTML'
END

